name: Pre-release version

on:
  push:
    branches: [alpha, beta, rc]

jobs:
  publish:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: fromTag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Installing python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installing poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.6.1'

      - name: Install deps
        run: poetry install

      - name: Run Dagger pipeline
        run: poetry run python main.py

      - name: Publish tag
        run: git push --tags

      - name: 'Get lastest tag'
        id: toTag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Run git-cliff
        run: |
          echo "CHANGELOG=$(git cliff)" >> $GITHUB_ENV

      - name: Display content
        run: echo $CHANGELOG

      # - name: Create Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     body: $CHANGELOG
      #     prerelease: true
      #     tag_name: ${{ steps.toTag.outputs.tag }}
